"""empty message

Revision ID: 1ad02832639f
Revises: eeac54e7b721
Create Date: 2020-08-08 11:54:11.404115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad02832639f'
down_revision = 'eeac54e7b721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('on_track', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_status_on_track'), 'status', ['on_track'], unique=False)
    op.drop_index('ix_status_onTrack', table_name='status')
    op.drop_column('status', 'onTrack')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('onTrack', sa.BOOLEAN(), nullable=True))
    op.create_index('ix_status_onTrack', 'status', ['onTrack'], unique=False)
    op.drop_index(op.f('ix_status_on_track'), table_name='status')
    op.drop_column('status', 'on_track')
    # ### end Alembic commands ###
