"""empty message

Revision ID: 2954cd544b0c
Revises: 
Create Date: 2020-08-10 06:12:56.359115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2954cd544b0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task', sa.String(length=500), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('onTrack', sa.Boolean(), nullable=True),
    sa.Column('cupdate', sa.String(length=500), nullable=True),
    sa.Column('issues', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_cupdate'), 'status', ['cupdate'], unique=False)
    op.create_index(op.f('ix_status_issues'), 'status', ['issues'], unique=False)
    op.create_index(op.f('ix_status_onTrack'), 'status', ['onTrack'], unique=False)
    op.create_index(op.f('ix_status_target'), 'status', ['target'], unique=False)
    op.create_index(op.f('ix_status_task'), 'status', ['task'], unique=False)
    op.create_index(op.f('ix_status_task_id'), 'status', ['task_id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('task', sa.String(length=500), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('onTrack', sa.Boolean(), nullable=True),
    sa.Column('cupdate', sa.String(length=500), nullable=True),
    sa.Column('issues', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_cupdate'), 'status_history', ['cupdate'], unique=False)
    op.create_index(op.f('ix_status_history_issues'), 'status_history', ['issues'], unique=False)
    op.create_index(op.f('ix_status_history_onTrack'), 'status_history', ['onTrack'], unique=False)
    op.create_index(op.f('ix_status_history_target'), 'status_history', ['target'], unique=False)
    op.create_index(op.f('ix_status_history_task'), 'status_history', ['task'], unique=False)
    op.create_index(op.f('ix_status_history_user_id'), 'status_history', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'task')
    )
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_task'), 'task', ['task'], unique=False)
    op.create_table('unique_i_ds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status_hist_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('pwd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_pwd'), 'user', ['pwd'], unique=False)
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_index(op.f('ix_user_pwd'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_table('unique_i_ds')
    op.drop_index(op.f('ix_task_task'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_status_history_user_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_task'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_target'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_onTrack'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_issues'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_cupdate'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_status_task_id'), table_name='status')
    op.drop_index(op.f('ix_status_task'), table_name='status')
    op.drop_index(op.f('ix_status_target'), table_name='status')
    op.drop_index(op.f('ix_status_onTrack'), table_name='status')
    op.drop_index(op.f('ix_status_issues'), table_name='status')
    op.drop_index(op.f('ix_status_cupdate'), table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
