"""empty message

Revision ID: 2b85b57c542a
Revises: 6752270c5db5
Create Date: 2020-08-08 04:50:38.329551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b85b57c542a'
down_revision = '6752270c5db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=500), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('onTrack', sa.Boolean(), nullable=True),
    sa.Column('cupdate', sa.String(length=500), nullable=True),
    sa.Column('issues', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_cupdate'), 'status', ['cupdate'], unique=False)
    op.create_index(op.f('ix_status_issues'), 'status', ['issues'], unique=False)
    op.create_index(op.f('ix_status_onTrack'), 'status', ['onTrack'], unique=False)
    op.create_index(op.f('ix_status_target'), 'status', ['target'], unique=False)
    op.create_index(op.f('ix_status_task'), 'status', ['task'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('pwd', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_pwd'), 'user', ['pwd'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pwd'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_status_task'), table_name='status')
    op.drop_index(op.f('ix_status_target'), table_name='status')
    op.drop_index(op.f('ix_status_onTrack'), table_name='status')
    op.drop_index(op.f('ix_status_issues'), table_name='status')
    op.drop_index(op.f('ix_status_cupdate'), table_name='status')
    op.drop_table('status')
    # ### end Alembic commands ###
