"""empty message

Revision ID: 59f65e53afd4
Revises: 2c7b1bc9c69f
Create Date: 2020-08-09 10:47:51.361635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f65e53afd4'
down_revision = '2c7b1bc9c69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('type', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_user_type'), 'user', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_type'), table_name='user')
    op.drop_column('user', 'type')
    # ### end Alembic commands ###
