"""empty message

Revision ID: 6752270c5db5
Revises: 
Create Date: 2020-08-08 04:37:17.757115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6752270c5db5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quoteauthor', sa.String(length=100), nullable=True),
    sa.Column('quotestring', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_quoteauthor'), 'quotes', ['quoteauthor'], unique=False)
    op.create_index(op.f('ix_quotes_quotestring'), 'quotes', ['quotestring'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotes_quotestring'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quoteauthor'), table_name='quotes')
    op.drop_table('quotes')
    # ### end Alembic commands ###
