"""empty message

Revision ID: 897b1e57ac51
Revises: 2954cd544b0c
Create Date: 2020-08-11 07:52:15.867624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '897b1e57ac51'
down_revision = '2954cd544b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'authenticated')
    # ### end Alembic commands ###
