"""empty message

Revision ID: eeac54e7b721
Revises: f9bff687e1fb
Create Date: 2020-08-08 09:13:32.652927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeac54e7b721'
down_revision = 'f9bff687e1fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
