"""empty message

Revision ID: f9bff687e1fb
Revises: 2b85b57c542a
Create Date: 2020-08-08 04:57:03.407470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9bff687e1fb'
down_revision = '2b85b57c542a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('task', sa.String(length=500), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('onTrack', sa.Boolean(), nullable=True),
    sa.Column('cupdate', sa.String(length=500), nullable=True),
    sa.Column('issues', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_cupdate'), 'status_history', ['cupdate'], unique=False)
    op.create_index(op.f('ix_status_history_issues'), 'status_history', ['issues'], unique=False)
    op.create_index(op.f('ix_status_history_onTrack'), 'status_history', ['onTrack'], unique=False)
    op.create_index(op.f('ix_status_history_target'), 'status_history', ['target'], unique=False)
    op.create_index(op.f('ix_status_history_task'), 'status_history', ['task'], unique=False)
    op.create_index(op.f('ix_status_history_user_id'), 'status_history', ['user_id'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(length=500), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_task'), 'task', ['task'], unique=False)
    op.add_column('status', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_status_task_id'), 'status', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_task_id'), table_name='status')
    op.drop_column('status', 'task_id')
    op.drop_index(op.f('ix_task_task'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_status_history_user_id'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_task'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_target'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_onTrack'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_issues'), table_name='status_history')
    op.drop_index(op.f('ix_status_history_cupdate'), table_name='status_history')
    op.drop_table('status_history')
    # ### end Alembic commands ###
